### ISSUE TITLE
Symfony 4

### ISSUE THREAD

**Issue by aziizoon** [martin-georgiev/social-post#3]
Hi,
Thank you for sharing this bundle with the community.
Is this version compatible with symfony4 ??
Thanks

**Comment by martin-georgiev** [comment]
I guess you are referring to https://packagist.org/packages/martin-georgiev/social-post-bundle, which is Symfony 4 compatible. The current repository provides a library with common usage pattern for posting on social media. For the Symfony bundle that integrates it please check [here](https://github.com/martin-georgiev/social-post-bundle).

**Comment by aziizoon** [comment]
Thanks ... it works for me !!
